import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import pluginNext from "@next/eslint-plugin-next";
import ts from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const eslintConfig = [
	// Configure global ignores (replaces .eslintignore)
	{
		ignores: [
			"node_modules/**",
			".cursor/**",
			".next/**",
			".vercel/**",
			".claude/**",
			"public/**",
			// tsconfig excludes (demo) examples; ESLint needs to match or it
			// can't find them in any TS project for type-aware linting.
			"src/app/(app)/(demo)/examples/**",
			"src/app/(demo)/**/*",
			// cli/ has its own tsconfig + toolchain and its deps aren't
			// installed by the root `bun install`; root tsconfig excludes it,
			// so type-aware linting can't resolve it here.
			"cli/**",
			"src/components/blocks/**",
			"src/components/ui/**",
			// Generated by `payload generate:types` — has tslint comments
			// and other style we don't enforce on generated code.
			"src/payload-types.ts",
			// Generated by fumadocs-mdx on every build; ships with @ts-nocheck
			// and isn't in the root tsconfig, so type-aware linting can't parse it.
			".source/**",
			// Standalone Holocron docs app — own tsconfig and toolchain, and its
			// dist/ is build output. See docs-site/README.md.
			"docs-site/**",
		],
	},

	// React flat config (avoids FlatCompat circular reference issue)
	{
		...pluginReact.configs.flat.recommended,
		settings: {
			react: { version: "detect" },
		},
		rules: {
			...(pluginReact.configs.flat.recommended?.rules ?? {}),
			// TS handles prop-types via types; the runtime prop-types lint rule is
			// noise here and produces 300+ false errors against typed components.
			"react/prop-types": "off",
		},
	},
	pluginReact.configs.flat["jsx-runtime"],

	// React Hooks
	{
		plugins: {
			"react-hooks": pluginReactHooks,
		},
		rules: pluginReactHooks.configs.recommended.rules,
	},

	// Next.js plugin (core-web-vitals includes recommended)
	{
		plugins: {
			"@next/next": pluginNext,
		},
		rules: {
			...pluginNext.configs.recommended.rules,
			...pluginNext.configs["core-web-vitals"].rules,
		},
	},

	// TypeScript files configuration
	{
		files: ["**/*.{ts,tsx}"],
		ignores: ["tests/**", "src/workers/**", "scripts/**"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: ["./tsconfig.json"],
				tsconfigRootDir: __dirname,
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		linterOptions: {
			reportUnusedDisableDirectives: true,
		},
		rules: {
			...(ts.configs["recommended-type-checked"]?.rules || {}),
			...(ts.configs["stylistic-type-checked"]?.rules || {}),
			"@typescript-eslint/no-unused-vars": [
				"warn",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
				},
			],
			"@typescript-eslint/consistent-type-imports": [
				"warn",
				{
					prefer: "type-imports",
					fixStyle: "inline-type-imports",
				},
			],
			"@typescript-eslint/ban-ts-comment": "warn",
			"@typescript-eslint/no-explicit-any": "warn",
			"@typescript-eslint/no-floating-promises": "warn",
			"@typescript-eslint/no-misused-promises": "warn",
			"@typescript-eslint/no-unsafe-argument": "warn",
			"@typescript-eslint/no-unsafe-assignment": "warn",
			"@typescript-eslint/no-unsafe-call": "warn",
			"@typescript-eslint/no-unsafe-member-access": "warn",
			"@typescript-eslint/no-unsafe-return": "warn",
		},
	},

	// Workers: use dedicated tsconfig for typed linting
	{
		files: ["src/workers/**/*.ts"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: ["./tsconfig.workers.json"],
				tsconfigRootDir: __dirname,
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: false,
				},
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
	},

	// Build-tooling scripts: tsconfig excludes scripts/ for the same reason as
	// tests. Use non-project parser config.
	{
		files: ["scripts/**/*.{ts,tsx,mts,mjs}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: null,
				ecmaVersion: "latest",
				sourceType: "module",
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		rules: {
			"@typescript-eslint/prefer-nullish-coalescing": "off",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-misused-promises": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/require-await": "off",
			"@typescript-eslint/no-base-to-string": "off",
			"@typescript-eslint/await-thenable": "off",
		},
	},

	// Tests: tsconfig excludes tests/ so type-aware linting can't parse them.
	// Use non-project parser config here to silence parser errors.
	{
		files: ["tests/**/*.{ts,tsx}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: null,
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		rules: {
			// Type-aware rules require parserOptions.project; explicitly disable
			// them here to match the non-project parser.
			"@typescript-eslint/prefer-nullish-coalescing": "off",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-misused-promises": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/require-await": "off",
			"@typescript-eslint/no-base-to-string": "off",
			"@typescript-eslint/await-thenable": "off",
		},
	},
];

export default eslintConfig;
