// next-env.d.ts is gitignored and only generated by `next dev`/`next build`,
// so a bare `tsc --noEmit` (CI typecheck) has no image module declarations.
/// <reference types="next/image-types/global" />
